# Generated by Django 5.1.2 on 2024-11-16 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_services_petprofile_petrecord_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='middle_name',
        ),
    ]
