# Generated by Django 5.1.2 on 2024-11-16 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_userprofile_middle_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='vaccination_status',
            field=models.CharField(choices=[('vaccinated', 'Vaccinated'), ('not_vaccinated', 'Not Vaccinated')], default='not_vaccinated', max_length=20),
        ),
        migrations.AlterField(
            model_name='petrecord',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='petrecord',
            name='vaccination_status',
            field=models.CharField(choices=[('vaccinated', 'Vaccinated'), ('not_vaccinated', 'Not Vaccinated')], default='not_vaccinated', max_length=20),
        ),
    ]
