# Generated by Django 5.1.2 on 2024-11-16 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_appointment_user_alter_petprofile_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petrecord',
            old_name='daily_activities',
            new_name='activities',
        ),
        migrations.RenameField(
            model_name='petrecord',
            old_name='health_notes',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='petrecord',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='petrecord',
            name='vaccination_status',
        ),
    ]
