# Generated by Django 5.1.2 on 2025-01-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petrecord',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
