# Generated by Django 5.1.2 on 2024-11-16 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_service_delete_services_alter_appointment_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Services',
        ),
    ]
