# Generated by Django 5.1.2 on 2025-01-31 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_petrecord_check_in_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petrecord',
            name='owner',
        ),
        migrations.AddField(
            model_name='petrecord',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
