# Generated by Django 5.1.2 on 2025-01-31 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_petrecord_owner_petrecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petrecord',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='petrecord',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
