# Generated by Django 5.1.2 on 2024-12-31 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_service_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='emergency_contact_number',
        ),
    ]
