# Generated by Django 5.1.2 on 2025-01-31 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_petrecord_check_in_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petrecord',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
