# Generated by Django 5.1.2 on 2025-01-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_petrecord_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='petprofile',
            name='pet_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
